
monadic = {
    "abs":              "A",
    "all":              "Ạ",
    "all_not_empty":    "Ȧ",
    "i_to_b":           "B",
    "b_to_i":           "Ḅ",
    "odd":              "Ḃ",
    "not":              "C",
    "ceil":             "Ċ",
    "i_to_d":           "D",
    "d_to_i":           "Ḍ",
    "tail":             "Ḋ",
    "all_eq":           "E",
    "any":              "Ẹ",
    "zip_idx":          "Ė",
    "flat":             "F",
    "floor":            "Ḟ",
    "grid":             "G", # don't know what this does
    "group":            "Ġ", # don't know what this does
    "half":             "H",
    "double":           "Ḥ",
    "head":             "Ḣ",
    "first_diff":       "I",
    "reciprocal":       "İ",
    "abs_le_one":       "Ị",
    "iota_len":         "J",
    "join_space":       "K",
    "split_space":      "Ḳ",
    "len":              "L",
    "iota_min":         "Ḷ",
    "idx_max":          "M",
    "min":              "Ṃ",
    "max":              "Ṁ",
    "neg":              "N",
    "println":          "Ṅ",
    "NOT":              "Ṇ",
    "ord":              "O",
    "chr":              "Ọ",
    "print":            "Ȯ",
    "prod_list":        "P",
    "pop":              "Ṗ",
    "uniq":             "Q",
    "iota":             "R",
    "rev":              "Ṛ",
    "print_str":        "Ṙ",
    "sum_list":         "S",
    "sign":             "Ṡ",
    "sort":             "Ṣ",
    "idx":              "T",
    "new_bool_arr":     "Ṭ",
    "last":             "Ṫ",
    "rev_arr":          "U",
    "grade_up":         "Ụ",
    "eval":             "V",
    "uneval":           "Ṿ", # don't know what this does
    "wrap":             "W",
    "sublists":         "Ẇ",
    "len_each":         "Ẉ",
    "rand_elem":        "X",
    "shuffle":          "Ẋ",
    "join_ln":          "Y",
    "split_ln":         "Ỵ",
    "tighten":          "Ẏ", # don't know what this does
    "columns":          "Z",
    "prep_zero":        "Ż",
    "is_prime":         "Ẓ",
    "sum_vect":         "§",
    "cumsum":           "Ä",
    "factorial":        "!",
    "bit_not":          "~",
    "sq":               "²",
    "sqrt":             "½",
    "deg_to_rad":       "°",
    "NOT_vect":         "¬",
    "add1":             "‘",
    "sub1":             "’",
    "identity":         "¹",
}

dyadic = {
    "+": "+",
    "_": "_",
    "*": "×",
    "div": "÷"
}
